#dimensionalpocketsii
modLoader="javafml"
loaderVersion="[39,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TheCosmicNebula/DimensionalPocketsII/issues"
logoFile="dimensional_logo.png"
	
[[mods]] #mandatory
	modId="dimensionalpocketsii"
	version="1.18.1-5.1.0.10"
	displayName="Dimensional Pockets II"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii"
	credits="NPException, VsnGamer (Elevator Code), Scarlet Spark, Apolybrium, Rechalow, Discord Members"
	authors="TheCosmicNebula" #optional
	description='''
Create pocket dimensions!
'''

[[dependencies.dimensionalpocketsii]]
    modId="cosmoslibrary"
    mandatory=true
    versionRange="[1.18.1-5.1.2,)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"

#cosmoslibrary
modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="cosmos_logo.png" #optional

[[mods]]
	modId="cosmoslibrary"
	version="1.18.1-5.1.2.50"
	displayName="Cosmos Library"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cosmos-library"
	authors="TheCosmicNebula"
	description='''
Library and API for TheCosmicNebula_'s Mods.
'''

[[dependencies.cosmoslibrary]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.cosmoslibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1]"
    ordering="NONE"
    side="BOTH"