#dimensionalpocketsii
modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="dimensional_logo.png" #optional
	
[[mods]] #mandatory
	modId="dimensionalpocketsii" #mandatory
	version="1.16.3-0.7.30" #mandatory
	displayName="Dimensional Pockets II" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii" #optional
	credits="NPException, Rechalow (Translation)" #optional
	authors="TheRealZeher" #optional
	description='''
	Create pocket dimensions!
	'''

[[dependencies.dimensionalpocketsii]] #optional
    modId="cosmoslibrary" #mandatory
    mandatory=true #mandatory
    versionRange="[1.16.3-2.1,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"

#cosmoslibrary
modLoader="javafml" #mandatory
loaderVersion="[34,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="cosmos_logo.png" #optional

[[mods]] #mandatory
	modId="cosmoslibrary" #mandatory
	version="1.16.3-2.1.65" #mandatory
	displayName="Cosmos Library" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cosmoslibrary" #optional
	authors="TheRealZeher" #optional
	description='''
	Library and API for TheRealZeher Mods.
	'''

[[dependencies.cosmoslibrary]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cosmoslibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
