#dimensionalpocketsii
modLoader="javafml" #mandatory
loaderVersion="[36.1,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="dimensional_logo.png" #optional
	
[[mods]] #mandatory
	modId="dimensionalpocketsii" #mandatory
	version="1.16.5-1.0.0" #mandatory
	displayName="Dimensional Pockets II" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii" #optional
	credits="NPException, Rechalow [Chinese Translation], Apolybrium, Scarlet Spark" #optional
	authors="TheCosmicNebula" #optional
	description='''
    Create pocket dimensions!
	'''

[[dependencies.dimensionalpocketsii]] #optional
    modId="cosmoslibrary" #mandatory
    mandatory=true #mandatory
    versionRange="[1.16.5-5.0,)" #mandatory
    ordering="BEFORE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"

#cosmoslibrary
modLoader="javafml" #mandatory
loaderVersion="[36.1,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="cosmos_logo.png" #optional

[[mods]] #mandatory
	modId="cosmoslibrary" #mandatory
	version="1.16.5-5.0.0" #mandatory
	displayName="Cosmos Library" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cosmoslibrary" #optional
	authors="TheCosmicNebula" #optional
	description='''
    Library and API for TheCosmicNebula's Mods.
	'''

[[dependencies.cosmoslibrary]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36.1,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cosmoslibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"
