#dimensionalpocketsii
modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/TheCosmicNebula/DimensionalPocketsII/issues"
logoFile="dimensional_logo.png"
	
[[mods]] #mandatory
	modId="dimensionalpocketsii"
	version="9.0.4.40"
	displayName="Dimensional Pockets II"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/dimensional-pockets-ii"
	credits="NPException, VsnGamer (Elevator Code), SuperMartijn642 (Chunkloading Code), Scarlet Spark, Apolybrium, Rechalow, Discord Members"
	authors="TheCosmicNebula_" #optional
	description='''
Create pocket dimensions!
'''

[[dependencies.dimensionalpocketsii]]
    modId="cosmoslibrary"
    mandatory=true
    versionRange="[10.3.1.0,11)"
    ordering="BEFORE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.dimensionalpocketsii]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21]"
    ordering="NONE"
    side="BOTH"

#cosmoslibrary
modLoader="javafml" #mandatory
loaderVersion="[47,)" #mandatory
license="All Rights Reserved" #mandatory
logoFile="cosmos_logo.png" #optional

[[mods]] #mandatory
	modId="cosmoslibrary" #mandatory
	version="10.3.1.0" #mandatory
	displayName="Cosmos Library" #mandatory
	displayURL="https://www.curseforge.com/minecraft/mc-mods/cosmos-library" #optional
	authors="TheCosmicNebula" #optional
	description='''
Library and API for TheCosmicNebula's Mods.
'''

[[dependencies.cosmoslibrary]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[47,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.cosmoslibrary]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1, 1.21]"
    ordering="NONE"
    side="BOTH"